### ISSUE TITLE
"Module not found" on location creation

### ISSUE THREAD

**Issue by tbluhmitsdave** [itsdave-de/msp#36]
Upon creating (saving) a new location (In this case type was street and an existing parent location was also selected) the following "Server Error" occours and the changes are not saved:

### App Versions
```
{
	"adnconnect": "0.0.1",
	"copconnect": "0.0.1",
	"erpnext": "13.46.1",
	"fieldservice": "0.0.1",
	"frappe": "13.49.2",
	"gdatames": "0.0.1",
	"hibiscus_connect": "0.0.1",
	"its_charging": "0.0.1",
	"ldapsync": "0.0.1",
	"msp": "0.0.1",
	"otrsconnect": "0.0.1",
	"tax_me": "0.0.1",
	"wiki": "0.0.1"
}
```
### Route
```
Form/Location/new-location-1
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1473, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 24, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 312, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 334, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 263, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1055, in run_before_save_methods
    self.run_method("before_save")
  File "apps/frappe/frappe/model/document.py", line 943, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1261, in composer
    hooks.append(frappe.get_attr(handler))
  File "apps/frappe/frappe/__init__.py", line 1463, in get_attr
    return getattr(get_module(modulename), methodname)
  File "apps/frappe/frappe/__init__.py", line 1205, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 981, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'msp.tools.hooks_methods'; 'msp.tools' is not a package

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Location\",\"name\":\"new-location-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"t.bluhm@itsdave.de\",\"type\":\"Street\",\"is_container\":0,\"is_group\":0,\"latitude\":19.08,\"longitude\":72.8961,\"location_name\":\"Heidberg 1\",\"parent_location\":\"Soltau\",\"location\":\"{\\\"type\\\":\\\"FeatureCollection\\\",\\\"features\\\":[{\\\"type\\\":\\\"Feature\\\",\\\"properties\\\":{},\\\"geometry\\\":{\\\"type\\\":\\\"Point\\\",\\\"coordinates\\\":[9.921234,52.98882]}}]}\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery224055993634080999381": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 4378,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "ModuleNotFoundError: No module named 'msp.tools.hooks_methods'; 'msp.tools' is not a package"
}
```

**Comment by itsdaveit** [comment]
seems like someone killed a lot of stuff last year: https://github.com/itsdave-de/msp/commit/9141df2e63acd3030d65676fc7b9d5d5760f3749
